[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["cdylib"]

[dependencies]
gl = "*"
miniserde = "0.1.12"
# yoga = "0.3.1"
# stretch = { path = "../../stretch" }
stretch = "0.3.2"
glfw = "0.27.0"
