[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["cdylib"]

[dependencies]
gl = "*"
miniserde = "0.1.12"
graffiti-yoga = { path = "graffiti-yoga" }
graffiti-glfw = { path = "graffiti-glfw" }

# npm run build -- --features stretch
stretch = { version = "0.3.2", optional = true }
# stretch = { path = "../../stretch", optional = true }

[features]
default = []
# include (desperate) debug msgs
debug = []
silly = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# fix raspi --release builds
# https://github.com/rust-lang/rust/issues/62896
codegen-units = 1
